import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const blowbrush = localFont({
  src: "../../public/fonts/blowbrush/blowbrush.ttf",
  variable: "--font-blowbrush",
});

const network = localFont({
  src: "../../public/fonts/NetworkFreeVersion.ttf",
  variable: "--font-network",
});

const bricolage = localFont({
  src: "../../public/fonts/Bricolage_Grotesque/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf",
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} ${blowbrush.variable} ${network.variable} ${bricolage.variable} antialiased font-[family-name:var(--font-bricolage)]`}
      >
        {children}
      </body>
    </html>
  );
}
